image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - step:
        name: Setup Environment
        image: python:3.8.1
        services:
          -  docker
        caches:
            - docker
            - pip
        script:
            - pip install docker-compose
            - docker-compose up -d
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet build KeyMashFramework.sln --configuration Debug
          - dotnet test KeyMashFramework.sln
            
definitions:
  services:
    docker:
      memory: 3072