image: mcr.microsoft.com/dotnet/core/sdk:5.0

pipelines:
  default:
    - step:
        caches: 
            - dotnetcore
        name: 'Build and Test'
        script:
        - dotnet restore KeyMashFramework.csproj
        - dotnet build KeyMashFramework.csproj