image: mcr.microsoft.com/dotnet/sdk:5.0

definitions:
  services:
    docker:
      memory: 512

pipelines:
  default:
    - parallel:
      - step:
          name: Setup Environment
          script:
            - docker-compose up
      - step:
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - dotnet build KeyMashFramework.sln --configuration Debug
            - dotnet test KeyMashFramework.sln