pipelines:
    default:
      - step:
          image: mcr.microsoft.com/dotnet/sdk:5.0
          name: Build and Test
          services:
            - chrome
          script:
            - dotnet build src/KeyMashFramework.sln
            - dotnet test src/KeyMashFramework.sln   
    branches:
      master:
      - step:
          image: mcr.microsoft.com/dotnet/sdk:5.0
          name: Build and Test
          services:
          - chrome
          script:
              - dotnet build src/KeyMashFramework.sln
              - dotnet test src/KeyMashFramework.sln --filter TestCategory=SmokeTest
         
definitions:
  services:
    chrome:
      image: selenium/standalone-chrome