image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - selenium-chrome
        caches:
          - dotnetcore
        script:
          - dotnet test KeyMashFramework.sln
            
definitions:
  services:
    selenium-chrome:
      image: selenium/standalone-chrome