image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  branches:
    develop:
      - step:
          name: Build and Test
          image: python:3.8.1
          services:
              -   docker
          caches:
              - docker
              - pip
              - dotnetcore
          script:
              - pip install docker-compose
              - docker-compose up -d
              - dotnet build KeyMashFramework.sln --configuration Debug
              - dotnet test KeyMashFramework.sln
            
definitions:
  services:
    docker:
      memory: 3072