pipelines:
  branches:
    develop:
      - step:
          image: mcr.microsoft.com/dotnet/sdk:5.0
          name: Build and Test
          services:
            - chrome
          script:
            - dotnet build KeyMashFramework.sln
            - dotnet test KeyMashFramework.sln
   
definitions:
  services:
    chrome:
      image: selenium/standalone-chrome