pipelines:
    default:
      - step:
          image: mcr.microsoft.com/dotnet/sdk:5.0
          name: Build and Test
          services:
            - hub
            - chrome
          script:
            - dotnet build KeyMashFramework.sln
            - dotnet test KeyMashFramework.sln   
    branches:
      master:
      - step:
          image: mcr.microsoft.com/dotnet/sdk:5.0
          name: Build and Test
          services:
          - chrome
          script:
          - dotnet build KeyMashFramework.sln
          - dotnet test KeyMashFramework.sln --filter TestCategory=SmokeTest


definitions:
  services:    
    hub:
      image: selenium/hub
    chrome:
      image: selenium/node-chrome